"""
Tools package - imports all tool modules so they register themselves.
Any reasoner that imports this gets all tools without knowing about Anthropic.
"""

from . import (
    filesystem,
    web_search,
    self_edit,
    gmail,
    discord,
    senses,
    runner,
    confluence,
    budget,
    github,
    openrouter_reasoner,
    browser,
    blobs,
    word_graph,
    metrics,
    training,
    cluster_ssh,
    notebook,
    ebook_reader,
    interpretive,
    google_calendar,
    google_contacts,
    hot_reload,
    learner,
    watchlist,
    traversal_context,
    os_primitives,
    slow_query,
    graph_ops,
    ops,
    converter,
    sudo_relay,
    memory_sync,
    reading_integration,
    trail_inspector,
    worker_foreman,
    template_tools,
    routing_tools,
    graph_write,
    self_trainer,
    output_trainer,
    stale_task_reaper,
    bootstrap_reader,
    training_pass,
    memory_query,
    boredom_idle,
    goal_continuation,
    pe_chain,
    habit_chunker,
    or_model_refresh,
    memory_snapshot,
    git_auth_check,
    thread_anchor,
    inhibition_seeder,
)
from ..arbiter import (
    queue as _arbiter_queue,
)  # noqa: F401 — registers arbiter_submit tool
