"""
Tagged blob storage tools — #65.

Igor can store full-content reference documents (research notes, code,
transcripts) with tags. Normal memory search discovers them via their
brief narrative; tag search retrieves the full content on demand.
"""

import json
import os
from pathlib import Path

from devices.igor.tools.registry import Tool, registry


def _get_cortex():
    """Get the cortex singleton from the running Igor instance."""
    from ..memory.cortex import Cortex

    return Cortex(None)


def store_reference(
    narrative: str,
    content: str,
    tags: str,
    **_,
) -> str:
    """
    Store a reference document with full content and tags.

    narrative: brief description (what this is, max 1-2 sentences)
    content: full text to preserve verbatim
    tags: comma-separated list of tags (e.g. "neuroscience,baddeley,working-memory")
    """
    try:
        tag_list = [t.strip() for t in tags.split(",") if t.strip()]
        cortex = _get_cortex()
        mem = cortex.store_blob(
            narrative=narrative,
            content=content,
            tags=tag_list,
        )
        return (
            f"Stored reference blob '{mem.id}'.\n"
            f"  Narrative: {narrative[:80]}\n"
            f"  Tags: {', '.join(tag_list)}\n"
            f"  Content length: {len(content)} chars\n"
            f"Retrieve with: get_reference(memory_id='{mem.id}') "
            f"or search_references(tags='{tags}')"
        )
    except Exception as e:
        return f"[ERROR storing blob] {e}"


def get_reference(memory_id: str, **_) -> str:
    """Retrieve full content of a reference blob by memory ID."""
    try:
        cortex = _get_cortex()
        content = cortex.get_blob(memory_id)
        if content is None:
            return f"No blob found for memory_id='{memory_id}'"
        mem = cortex.get(memory_id)
        header = (
            f"[{memory_id}] {mem.narrative if mem else '(narrative not found)'}\n\n"
        )
        return header + content
    except Exception as e:
        return f"[ERROR retrieving blob] {e}"


def search_references(tags: str, match_all: bool = False, **_) -> str:
    """
    Search reference blobs by tag.

    tags: comma-separated tags to search for
    match_all: if true, only return blobs matching ALL tags (default: any)
    """
    try:
        tag_list = [t.strip() for t in tags.split(",") if t.strip()]
        cortex = _get_cortex()
        results = cortex.search_by_tags(tag_list, match_all=bool(match_all))
        if not results:
            return f"No reference blobs found matching tags: {', '.join(tag_list)}"
        lines = [
            f"Found {len(results)} reference blob(s) matching [{', '.join(tag_list)}]:"
        ]
        for r in results:
            lines.append(
                f"\n  [{r['memory_id']}] {r['narrative'][:80]}\n"
                f"    Tags: {', '.join(r['tags'])}\n"
                f"    Preview: {r['content_preview'][:120]}...\n"
                f"    Use get_reference(memory_id='{r['memory_id']}') for full content"
            )
        return "\n".join(lines)
    except Exception as e:
        return f"[ERROR searching blobs] {e}"


def store_design_doc_pair(
    name: str, csb_content: str, distilled_content: str, model_id: str = "unknown", **_
) -> str:
    """
    Store a design doc as two blobs (#68): raw CSB + model-tagged distilled summary.

    name: short identifier (e.g. "mission", "architecture")
    csb_content: full authoritative CSB source
    distilled_content: compact summary generated by model_id
    model_id: model that created the distilled version (for cache-miss detection)
    """
    try:
        cortex = _get_cortex()
        raw_mem, dist_mem = cortex.store_blob_pair(
            name=name,
            raw_content=csb_content,
            distilled_content=distilled_content,
            model_id=model_id,
        )
        return (
            f"Stored design doc pair for '{name}':\n"
            f"  Raw (CSB):   [{raw_mem.id}] {len(csb_content)} chars → tags: design_doc,csb,{name}\n"
            f"  Distilled:   [{dist_mem.id}] {len(distilled_content)} chars → tags: design_doc,distilled,{name},model={model_id}\n"
            f"Load with: load_design_doc(name='{name}', model_id='{model_id}')"
        )
    except Exception as e:
        return f"[ERROR storing design doc pair] {e}"


def load_design_doc(name: str, model_id: str = "", **_) -> str:
    """
    Smart-load a design doc (#68).

    Priority: distilled blob (matching model_id) → raw CSB blob → filesystem fallback.
    On model mismatch, returns raw CSB with a note to regenerate distilled.

    name: design doc name (e.g. "mission", "architecture")
    model_id: current model ID — used to match distilled blob cache
    """
    try:
        cortex = _get_cortex()

        # Try distilled first if model_id provided
        if model_id:
            distilled = cortex.search_by_tags(
                [f"model={model_id}", "distilled", name], match_all=True
            )
            if distilled:
                mem_id = distilled[0]["memory_id"]
                content = cortex.get_blob(mem_id)
                if content:
                    return f"[DISTILLED:{name}|model={model_id}]\n\n{content}"

        # Fall back to raw CSB blob
        raw = cortex.search_by_tags(["csb", name, "design_doc"], match_all=True)
        if raw:
            mem_id = raw[0]["memory_id"]
            content = cortex.get_blob(mem_id)
            if content:
                note = (
                    f"\n\n[NOTE: distilled not found for model={model_id or '?'} — regenerate with store_design_doc_pair]"
                    if model_id
                    else ""
                )
                return f"[RAW_CSB:{name}]{note}\n\n{content}"

        # Filesystem fallback
        from pathlib import Path as _Path

        repo_root = _Path(__file__).parent.parent.parent.parent
        for fname in [f"{name}.csb.txt", f"{name}.txt", f"design_docs/{name}.csb.txt"]:
            fpath = repo_root / fname
            if fpath.exists():
                return f"[FILESYSTEM:{fpath}]\n\n{fpath.read_text()}"

        return f"Design doc '{name}' not found in blobs or filesystem. Store it first with store_design_doc_pair()."
    except Exception as e:
        return f"[ERROR loading design doc] {e}"


def list_reference_tags(**_) -> str:
    """List all tags used across reference blobs, with counts."""
    try:
        cortex = _get_cortex()
        counts = cortex.list_blob_tags()
        if not counts:
            return "No reference blobs stored yet."
        lines = ["Reference blob tags (most used first):"]
        for tag, count in counts.items():
            lines.append(f"  {tag}: {count}")
        return "\n".join(lines)
    except Exception as e:
        return f"[ERROR listing tags] {e}"


# ── Register tools ─────────────────────────────────────────────────────────────

registry.register(
    Tool(
        name="store_reference",
        description=(
            "Store a reference document (research notes, code, transcripts, full articles) "
            "with a brief narrative description and comma-separated tags. "
            "The narrative participates in normal memory search; "
            "the full content is retrievable by tag or memory ID. "
            "Use this when you want to preserve something verbatim for later retrieval."
        ),
        parameters={
            "type": "object",
            "properties": {
                "narrative": {
                    "type": "string",
                    "description": "Brief description: what this is and why it matters (1-2 sentences)",
                },
                "content": {
                    "type": "string",
                    "description": "Full verbatim content to preserve",
                },
                "tags": {
                    "type": "string",
                    "description": "Comma-separated tags, e.g. 'neuroscience,baddeley,working-memory'",
                },
            },
            "required": ["narrative", "content", "tags"],
        },
        fn=store_reference,
    )
)

registry.register(
    Tool(
        name="get_reference",
        description="Retrieve full content of a stored reference blob by its memory ID.",
        parameters={
            "type": "object",
            "properties": {
                "memory_id": {
                    "type": "string",
                    "description": "The 8-character memory ID returned when the blob was stored",
                },
            },
            "required": ["memory_id"],
        },
        fn=get_reference,
    )
)

registry.register(
    Tool(
        name="search_references",
        description=(
            "Search stored reference blobs by tag. "
            "Returns matching blobs with previews and memory IDs. "
            "Use get_reference() to fetch full content."
        ),
        parameters={
            "type": "object",
            "properties": {
                "tags": {
                    "type": "string",
                    "description": "Comma-separated tags to search for",
                },
                "match_all": {
                    "type": "boolean",
                    "description": "If true, only return blobs matching ALL tags (default: any tag matches)",
                },
            },
            "required": ["tags"],
        },
        fn=search_references,
    )
)

registry.register(
    Tool(
        name="list_reference_tags",
        description="List all tags used across stored reference blobs, with usage counts.",
        parameters={"type": "object", "properties": {}, "required": []},
        fn=list_reference_tags,
    )
)

registry.register(
    Tool(
        name="store_design_doc_pair",
        description=(
            "Store a design document as two blobs: authoritative raw CSB + compact distilled summary. "
            "The distilled version is model-tagged for cache-miss detection. "
            "Use when storing/updating any design_docs/*.csb.txt content."
        ),
        parameters={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Short identifier, e.g. 'mission' or 'architecture'",
                },
                "csb_content": {
                    "type": "string",
                    "description": "Full authoritative CSB source text",
                },
                "distilled_content": {
                    "type": "string",
                    "description": "Compact summary (~60-70% fewer tokens)",
                },
                "model_id": {
                    "type": "string",
                    "description": "Model ID that generated the distilled version",
                },
            },
            "required": ["name", "csb_content", "distilled_content"],
        },
        fn=store_design_doc_pair,
    )
)

registry.register(
    Tool(
        name="load_design_doc",
        description=(
            "Smart-load a design document. Checks distilled blob (model-matched) first, "
            "then raw CSB blob, then filesystem. Pass model_id for cache-hit detection."
        ),
        parameters={
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Design doc name, e.g. 'mission' or 'architecture'",
                },
                "model_id": {
                    "type": "string",
                    "description": "Current model ID (for distilled cache lookup)",
                },
            },
            "required": ["name"],
        },
        fn=load_design_doc,
    )
)
