"""
Tools package - imports all tool modules so they register themselves.
Any reasoner that imports this gets all tools without knowing about Anthropic.
"""

from . import (
    web_search,
    self_edit,
    gmail,
    discord,
    senses,
    runner,
    confluence,
    github,
    openrouter_reasoner,
    browser,
    blobs,
    word_graph,
    metrics,
    training,
    cluster_ssh,
    notebook,
    ebook_reader,
    interpretive,
    google_calendar,
    google_contacts,
    hot_reload,
    learner,
    watchlist,
    traversal_context,
    os_primitives,
    slow_query,
    graph_ops,
    ops,
    converter,
    memory_sync,
    reading_integration,
    trail_inspector,
    worker_foreman,
    template_tools,
    routing_tools,
    graph_write,
    self_trainer,
    output_trainer,
    stale_task_reaper,
    bootstrap_reader,
    memory_query,
    boredom_idle,
    goal_continuation,
    after_action_reviewer,
    habit_chunker,
    or_model_refresh,
    memory_snapshot,
    git_auth_check,
    thread_anchor,
    inhibition_seeder,
    urgency_provenance,
    memory_provenance,
    deferred_self_task,
    skill_filter,
    skill_importer,
    receive_cc_direction,
    cloud_escape_metric,
    memory_palace,
    reading_measure,
    reading_tool,
    habit_health_audit,
    instance_tracker,
    goal_graph,
    tiered_research,
    hardware_detect,
    self_inspect,
    share_pattern,
)
from ..arbiter import (
    queue as _arbiter_queue,
)  # noqa: F401 — registers arbiter_submit tool
from . import engram_log  # noqa: F401 — registers engram_log tool
