"""first_start.py — first-start wizard (D108).

Called by the igor bash script when no .env is found.
Prompts for instance name and DB host, creates the instance directory,
and writes a minimal .env file.

Usage (from bash):
    python3 wild_igor/igor/first_start.py
Exit codes:
    0 — .env written successfully (caller should re-source it)
    1 — user aborted or error
"""

from __future__ import annotations

import os
import sys
from datetime import datetime
from pathlib import Path


def _prompt(label: str, default: str) -> str:
    """Prompt with a default shown in brackets. Empty input → use default."""
    try:
        val = input(f"{label} [{default}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\n[igor] Aborted.", file=sys.stderr)
        sys.exit(1)
    return val if val else default


def run() -> None:
    runtime_root = os.getenv("IGOR_RUNTIME_ROOT", str(Path.home() / ".TheIgors"))
    runtime = Path(runtime_root).expanduser().resolve()

    print("[igor] First-start setup")
    print(f"[igor] Runtime root: {runtime}")
    print()

    # --- Instance name ---
    ts = datetime.now().strftime("%Y%m%d%H%M%S")
    default_name = f"wild_igor_{ts}"
    raw_name = _prompt("Instance name", default_name)
    # Normalise: strip leading "igor_" if user typed it (we add it for folder)
    instance_short = raw_name.lstrip()
    # Folder name is igor_{instance_short} unless user typed the full igor_ prefix
    if instance_short.startswith("igor_"):
        folder_name = instance_short
    else:
        folder_name = f"igor_{instance_short}"

    # --- DB host ---
    db_host = _prompt("Database host", "127.0.0.1")

    # --- Create instance directory ---
    instance_dir = runtime / folder_name
    instance_dir.mkdir(parents=True, exist_ok=True)

    env_path = instance_dir / ".env"

    # Derive the DB path
    db_name = instance_short.replace("-", "_")
    db_path = instance_dir / f"{db_name}.db"

    # --- Write .env ---
    env_content = f"""\
# Igor instance environment — generated by first_start.py
# Instance: {folder_name}

IGOR_INSTANCE_ID={folder_name}
IGOR_RUNTIME_ROOT={runtime}
IGOR_DB_PATH={db_path}

# Inference — fill in your keys
OPENROUTER_API_KEY=
ANTHROPIC_API_KEY=

# DB host (for future multi-node use)
IGOR_DB_HOST={db_host}

# Feature gates (defaults — change as needed)
IGOR_SELF_EDIT_ENABLED=false
IGOR_TIER5_ENABLED=false
IGOR_ARBITER_ENABLED=false
IGOR_DUAL_WORD_GRAPHS=true
IGOR_NPASS_REPLY=true
IGOR_COMPREHENSION_SIGNAL=true
IGOR_MAX_TURNS=8
IGOR_RESEARCH_MODE=false

# Models
OPENROUTER_CHEAP_MODEL=gpt-4o-mini
OPENROUTER_DEFAULT_MODEL=claude-haiku-4-5-20251001
OPENROUTER_INTERACTIVE_MODEL=claude-sonnet-4-6
OLLAMA_LOCAL_MODEL=qwen2.5:7b
"""

    env_path.write_text(env_content)

    print()
    print(f"[igor] Instance directory created: {instance_dir}")
    print(f"[igor] .env written to: {env_path}")
    print()
    print("[igor] Next steps:")
    print(f"  1. Edit {env_path} — add your OPENROUTER_API_KEY / ANTHROPIC_API_KEY")
    print("  2. Run: igor")
    print()

    # Print the env path so the bash caller can pick it up
    print(f"IGOR_ENV_FILE={env_path}")


if __name__ == "__main__":
    run()
