"""
corpus_verdict.py — the ground-truth join: attach a reality-graded verdict_strength
to inference I/O corpus entries.

io_corpus records carry the join key (``ticket_id``) but only a TRANSPORT outcome
(ok/timeout/error) — never a correctness verdict. So replay can prove FIDELITY
(reproduce what the model said) but not CORRECTNESS (produce a working output). Any
starve-curve scored on the raw corpus is self-consistent, not ground-truth-closed.

This module is the join that closes that gap. It is a SEPARATE reader/enrichment
layer — it reads the corpus JSONL + the flat-file proof/ticket stores and stamps a
``verdict_strength`` on each entry. It never touches the hot dispatch path
(``device.py``); io_corpus stays the honest frozen-past ledger, and the grounding
comes from joining each entry to a verdict generated by a DIFFERENT process than the
one that produced the answer (see D-proof-program-grounding-spine-2026-07-05).

verdict_strength is COUPLING-TO-REALITY strength, NOT code quality. Higher is
more-grounded, not "better": ``consequence_bearing`` routinely means "the code was
wrong and a later commit corrected it." A reader must never treat the top code rung
as a quality badge.

CP1 residue — two rungs have NO ticket-attributable witness today, so the default
source leaves them dark rather than fabricate them (named levers, not silent zeros):
  * executed_live — no ticket-attributable runtime-execution capture. Git ancestry
    ("proof commit is an ancestor of HEAD") is NOT a substitute: on a
    commit-to-main-every-ticket repo it means "wasn't reverted", not "ran", and it is
    a same-time fact (the commit exists at close), so it is weaker-grounded than the
    future-fact rung above it. Left False until a runtime witness (log/import capture
    keyed by ticket) lands.
  * akien_noticed — no automated human-signal join yet. Left False.
The resulting ``executed_live: 0`` in the histogram is a TRUTHFUL measurement of a
missing instrument, in the spirit of the program — not a placeholder.
"""

from __future__ import annotations

import json
import logging
import subprocess
from collections import Counter
from dataclasses import dataclass
from enum import IntEnum
from pathlib import Path
from typing import Optional

from unseen_university import proof_store, ticket_store
from unseen_university._uu_root import uu_root

log = logging.getLogger(__name__)


class VerdictStrength(IntEnum):
    """How tightly a corpus entry's outcome is COUPLED TO REALITY — ordered weakest→strongest.

    - LLM_SAID_IT          the model emitted output; no external witness. The floor.
    - TEST_GREEN           a red→green proof passed for the ticket (system-authored test).
    - EXECUTED_LIVE        the shipped code demonstrably ran — LIVENESS ONLY (didn't crash),
                           NOT correctness.
    - CONSEQUENCE_BEARING  the code path provoked subsequent action on its own lines — it ran
                           where wrongness WOULD HAVE surfaced. A FUTURE fact the close-time
                           model cannot manufacture (the temporal firewall).
    - AKIEN_NOTICED        a human-origin verdict referenced the ticket. Un-fakeable friction.
    """

    LLM_SAID_IT = 0
    TEST_GREEN = 1
    EXECUTED_LIVE = 2
    CONSEQUENCE_BEARING = 3
    AKIEN_NOTICED = 4


# The ticket's reality-tested view excludes only LLM_SAID_IT (entries with any external witness).
REALITY_TESTED_FLOOR = VerdictStrength.TEST_GREEN
# The firewall-grounded subset — future-fact rungs only. This is the PRIMARY grounding metric
# the consequence ticket watches (zero today; must become >0 for the thesis to touch ground).
FIREWALL_FLOOR = VerdictStrength.CONSEQUENCE_BEARING


@dataclass
class VerdictEvidence:
    """The per-ticket evidence bundle the classifier maps to a VerdictStrength.

    Each flag is the SUFFICIENT signal for its rung. The default GitEvidenceSource can
    witness ``has_green_proof`` and ``consequence_signal`` from the flat-file proof store
    + git; ``executed_live`` and ``akien_signal`` have no ticket-attributable capture yet
    and are left False (named levers — see module docstring). They remain reachable through
    an injected source once a runtime/human witness lands, so the classifier supports them.
    """

    has_green_proof: bool = False
    executed_live: bool = False
    consequence_signal: bool = False
    akien_signal: bool = False


def classify(ev: VerdictEvidence) -> VerdictStrength:
    """Map evidence to the STRONGEST rung whose sufficient signal is present.

    Each rung carries its own sufficient signal; a stronger rung does not require an
    independent witness for the weaker one below it (``consequence_bearing`` does not
    need a separate ``executed_live`` witness — a later commit on the same lines is itself
    proof the code ran and mattered).

    The load-bearing discrimination: LIVENESS (``executed_live``) is NOT CONSEQUENCE
    (``consequence_signal``). A naive classifier that treats mere execution/presence as
    consequence conflates rungs 2 and 3 and silently re-imports the self-consistency trap.
    """
    if ev.akien_signal:
        return VerdictStrength.AKIEN_NOTICED
    if ev.consequence_signal:
        return VerdictStrength.CONSEQUENCE_BEARING
    if ev.executed_live:
        return VerdictStrength.EXECUTED_LIVE
    if ev.has_green_proof:
        return VerdictStrength.TEST_GREEN
    return VerdictStrength.LLM_SAID_IT


def _has_green_gate(proof: dict) -> bool:
    gates = (proof.get("body") or {}).get("gates") or []
    return any((g or {}).get("result") == "green" for g in gates)


class GitEvidenceSource:
    """Derive VerdictEvidence from the flat-file proof store + git history.

    Honest coverage (CP1) — only two rungs have a ticket-attributable witness today:
      has_green_proof    — a proof envelope with a green gate exists for the ticket.
      consequence_signal — a commit AFTER the green proof's commit touched that proof's
                           ``impl_paths`` (``git log <commit>..HEAD -- <impl_paths>`` is
                           non-empty): the code path provoked later action on its own lines.

    Deliberately NOT derived (missing levers — left False, never fabricated from topology):
      executed_live, akien_signal. See the module docstring for why git ancestry is not a
      substitute for a runtime-execution witness.
    """

    def __init__(self, repo_root: Optional[str] = None):
        self._repo_root = repo_root or uu_root()

    def evidence_for(self, ticket_id: str) -> VerdictEvidence:
        if not ticket_id:
            return VerdictEvidence()
        green_proofs = [p for p in proof_store.find_for_ticket(ticket_id) if _has_green_gate(p)]
        return VerdictEvidence(
            has_green_proof=bool(green_proofs),
            consequence_signal=any(self._touched_since(p) for p in green_proofs),
            # executed_live / akien_signal: no ticket-attributable witness — see docstring.
        )

    def _touched_since(self, proof: dict) -> bool:
        """True iff a commit after the proof's commit touched the proof's impl_paths."""
        body = proof.get("body") or {}
        commit = body.get("commit") or ((proof.get("links") or {}).get("commits") or [None])[0]
        impl_paths = body.get("impl_paths") or []
        if not commit or not impl_paths:
            return False
        r = subprocess.run(
            ["git", "-C", self._repo_root, "log", "--oneline", f"{commit}..HEAD", "--", *impl_paths],
            capture_output=True,
            text=True,
        )
        if r.returncode != 0:
            # unknown commit / detached history / git error — no positive signal.
            # Fail-closed on the strong rung: never invent consequence from an error.
            return False
        return bool(r.stdout.strip())


class CorpusVerdictReader:
    """Join io_corpus entries to a reality-graded verdict_strength and expose the
    reality-tested view. A SEPARATE reader — it never touches the dispatch path.
    """

    def __init__(self, corpus_root=None, evidence_source=None):
        from unseen_university.devices.inference.io_corpus import corpus_root as _default_corpus_root

        self._corpus_root = Path(corpus_root) if corpus_root else _default_corpus_root()
        self._source = evidence_source or GitEvidenceSource()
        self._evidence_cache: "dict[str, VerdictEvidence]" = {}

    def _iter_corpus(self):
        if not self._corpus_root.exists():
            return
        for f in sorted(self._corpus_root.glob("*.io.jsonl")):
            for line in f.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line)
                except Exception as exc:  # unreadable line — skip, never crash a read
                    log.warning("corpus_verdict: unreadable corpus line in %s: %s", f.name, exc)

    def _verdict_for_ticket(self, ticket_id: str) -> VerdictStrength:
        if ticket_id not in self._evidence_cache:
            self._evidence_cache[ticket_id] = self._source.evidence_for(ticket_id)
        return classify(self._evidence_cache[ticket_id])

    def enrich(self) -> "list[dict]":
        """Return each corpus record stamped with ``verdict_strength`` (the rung name).

        Emits the join summary at INFO — it points straight at the join if the
        reality-tested view comes back empty (all entries LLM_SAID_IT / unlinkable).
        """
        out: "list[dict]" = []
        hist: Counter = Counter()
        unlinkable = 0
        for rec in self._iter_corpus():
            tid = rec.get("ticket_id") or ""
            linked = bool(tid) and ticket_store.read(tid) is not None
            if not linked:
                unlinkable += 1
                verdict = VerdictStrength.LLM_SAID_IT
            else:
                verdict = self._verdict_for_ticket(tid)
            hist[verdict.name] += 1
            out.append({**rec, "verdict_strength": verdict.name})
        log.info(
            "corpus_verdict: joined %d entries, stamped by strength "
            "{llm_said_it:%d, test_green:%d, executed_live:%d, consequence_bearing:%d, "
            "akien_noticed:%d}, excluded %d unlinkable",
            len(out),
            hist.get("LLM_SAID_IT", 0),
            hist.get("TEST_GREEN", 0),
            hist.get("EXECUTED_LIVE", 0),
            hist.get("CONSEQUENCE_BEARING", 0),
            hist.get("AKIEN_NOTICED", 0),
            unlinkable,
        )
        return out

    def reality_tested_view(self) -> "list[dict]":
        """Enriched entries at or above TEST_GREEN — LLM_SAID_IT excluded (the ticket's
        reality-tested filter). The firewall-grounded subset (>= FIREWALL_FLOOR) is the
        PRIMARY grounding metric; filter on ``verdict_strength`` against FIREWALL_FLOOR."""
        return [
            r for r in self.enrich()
            if VerdictStrength[r["verdict_strength"]] >= REALITY_TESTED_FLOOR
        ]
